<?php
/**
 * AgentGuidance — CLAUDE.md is generated, not maintained.
 *
 * Learned from Laravel Boost (COMPONENTS_PLAN.md, "Concept guidance"): agent guidance is
 * composed from what an install HAS, and regenerated when that changes. Here:
 *
 *   agent/guidelines/NN-<section>.md     core guidance, one file per section, in order
 *   concepts/<name>/guidelines.md        an enabled concept's own rules (≤ MAX_LINES)
 *
 * sync() rewrites ONE managed block in <root>/CLAUDE.md, between START and END. Whatever
 * is above START — capricorn's "your private instance" preamble, the operator's notes — is
 * kept byte for byte. Core's own CLAUDE.md is the same output with zero concepts, which is
 * how the split was proven: compose(core) had to reproduce the hand-written file.
 *
 * A file with no markers is migrated once, and only from a layout this class recognises
 * (core's, or capricorn's provisioning layout). Anything else is refused with the two
 * marker lines to add by hand — appending a block under an unknown body would duplicate
 * guidance an agent then reads twice, and that is worse than stopping.
 *
 * Pure functions over paths: nothing here reads a database. The caller (clitool, Concepts)
 * says which concepts are enabled.
 */

namespace app;

class AgentGuidance {

    public const FILE  = 'CLAUDE.md';
    public const DIR   = 'agent/guidelines';
    public const START = '<!-- tiknix:managed start — generated by `php scripts/clitool.php --agent-sync`; edit agent/guidelines/ instead -->';
    public const END   = '<!-- tiknix:managed end -->';

    /** A concept's guidelines.md is loaded every session; the long form belongs in a skill. */
    public const MAX_LINES = 80;
    public const CONCEPT_FILE = 'guidelines.md';

    /** capricorn's provision-instance.sh appends the app's CLAUDE.md under this heading. */
    private const LEGACY_SEAM = '## App technical notes (from the source app)';
    /** Core's hand-written file began with this H1; it stays as core's preamble. */
    private const CORE_H1 = '# Tiknix Development Standards';

    /**
     * Core's sections, in order: ['10-top-rules.md' => "## Top Rules\n…", …].
     * Loud when the directory is missing — an install with no guidance is a fault, not an
     * empty block.
     */
    public static function sections(string $root): array {
        $dir = rtrim($root, '/') . '/' . self::DIR;
        if (!is_dir($dir)) {
            throw new \RuntimeException("AgentGuidance: {$dir} does not exist. Core guidance lives there, one file per section.");
        }
        $files = glob($dir . '/*.md') ?: [];
        if (!$files) {
            throw new \RuntimeException("AgentGuidance: {$dir} has no *.md sections.");
        }
        sort($files, SORT_STRING);
        $out = [];
        foreach ($files as $f) {
            $body = file_get_contents($f);
            if ($body === false) throw new \RuntimeException("AgentGuidance: could not read {$f}.");
            if (!preg_match('/^## \S/', $body)) {
                throw new \RuntimeException("AgentGuidance: " . basename($f) . " must start with its '## Heading' line.");
            }
            $out[basename($f)] = $body;
        }
        return $out;
    }

    /**
     * The managed block: core sections, then one "## Concept: <name> (<version>)" section per
     * enabled concept that ships guidelines.md.
     *
     * @param array<string,array{version:string,dir:string}> $concepts  enabled, in registry order
     * @return array{block:string,notes:string[]}  notes: concepts enabled without guidelines
     */
    public static function managedBlock(string $root, array $concepts): array {
        $parts = [self::START . "\n"];
        foreach (self::sections($root) as $body) $parts[] = rtrim($body, "\n") . "\n\n";
        $notes = [];
        foreach ($concepts as $name => $c) {
            $file = rtrim($c['dir'], '/') . '/' . self::CONCEPT_FILE;
            if (!is_file($file)) {
                $notes[] = "concept '{$name}' is enabled but has no " . self::CONCEPT_FILE . " — agents get no guidance for it (required to publish).";
                continue;
            }
            $text = trim((string) file_get_contents($file));
            $lines = substr_count($text, "\n") + 1;
            if ($lines > self::MAX_LINES) {
                throw new \RuntimeException("AgentGuidance: {$file} is {$lines} lines; the limit is " . self::MAX_LINES . '. Move the long form to a skill.');
            }
            if (preg_match('/^## /m', $text)) {
                throw new \RuntimeException("AgentGuidance: {$file} contains a '## ' heading; a concept's guidance is one section (use ### inside it).");
            }
            $parts[] = "## Concept: {$name} ({$c['version']})\n\n{$text}\n\n";
        }
        $parts[] = self::END . "\n";
        return ['block' => implode('', $parts), 'notes' => $notes];
    }

    /**
     * The file as it should be: the current preamble + a fresh managed block.
     *
     * @return array{text:string,notes:string[],migrated:bool}
     */
    public static function compose(string $root, array $concepts): array {
        $path = rtrim($root, '/') . '/' . self::FILE;
        $existing = is_file($path) ? (string) file_get_contents($path) : '';
        [$preamble, $migrated] = self::preambleOf($existing, $path);
        $b = self::managedBlock($root, $concepts);
        return ['text' => $preamble . $b['block'], 'notes' => $b['notes'], 'migrated' => $migrated];
    }

    /**
     * Rewrite <root>/CLAUDE.md. Idempotent: an unchanged result is not written.
     *
     * @return array{changed:bool,path:string,notes:string[],migrated:bool}
     */
    public static function sync(string $root, array $concepts): array {
        $path = rtrim($root, '/') . '/' . self::FILE;
        $c = self::compose($root, $concepts);
        $current = is_file($path) ? (string) file_get_contents($path) : null;
        $changed = $current !== $c['text'];
        if ($changed && file_put_contents($path, $c['text']) === false) {
            throw new \RuntimeException("AgentGuidance: could not write {$path}.");
        }
        return ['changed' => $changed, 'path' => $path, 'notes' => $c['notes'], 'migrated' => $c['migrated']];
    }

    /**
     * What stays above the block. [$preamble, $migrated]
     *
     * With markers: everything before START (the block and anything after END are ours to
     * regenerate; text after END is dropped, and that is deliberate — the end marker is the
     * end of the file, so a note wants to go above START).
     */
    private static function preambleOf(string $existing, string $path): array {
        if ($existing === '') return ['', false];
        $s = strpos($existing, self::START);
        if ($s !== false) {
            if (strpos($existing, self::END, $s) === false) {
                throw new \RuntimeException("AgentGuidance: {$path} has the start marker but no end marker. Restore the end marker, or delete the block.");
            }
            return [substr($existing, 0, $s), false];
        }
        // No markers: a file from before sync existed. Two layouts are known.
        $seam = strpos($existing, "\n" . self::LEGACY_SEAM . "\n");
        if ($seam !== false) {
            // capricorn: preamble, then "---", then the seam heading, then the old core body.
            $pre = substr($existing, 0, $seam);
            $pre = rtrim(preg_replace('/\n---\s*$/', '', rtrim($pre))) . "\n\n";
            return [$pre, true];
        }
        if (str_starts_with($existing, self::CORE_H1 . "\n")) {
            return [self::CORE_H1 . "\n\n", true];
        }
        throw new \RuntimeException(
            "AgentGuidance: {$path} has no managed block and is not a layout this can migrate. "
          . "Put these two lines where the generated guidance should go, then run --agent-sync again:\n"
          . self::START . "\n" . self::END);
    }

    /** True when <root>/CLAUDE.md carries the managed block. */
    public static function isManaged(string $root): bool {
        $path = rtrim($root, '/') . '/' . self::FILE;
        return is_file($path) && str_contains((string) file_get_contents($path), self::START);
    }
}
